### ISSUE TITLE
swarm-actions 1.0

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/js-team-zenhub#105]
TODO:
- [x] pr comment action
- [x] move to ethersphere org - @AuHau and @filozoom to be code owner
- [x] deprecate the bee-load action
- [x] replace in all our repos
