### ISSUE TITLE
gateway release

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/js-team-zenhub#107]
- [x] optimal postage price for the gateway
    - at minimum larger than the transaction cost
    - consider also increasing the amount (are there any technical limits - e.g. pull sync bugs)
    - the stamps take on average 4 days to be full
    - currently the transaction cost to buy stamp are `0.000255255 + 0.000560855 = 0.00081611` xDAI so with current tx costs we want at minimum `0.001 BZZ` stamp price (so at minimum depth `20` and amount `10 000 000` - just as we have on the gateway) 
        - [approve tx](https://blockscout.com/xdai/mainnet/tx/0xf10427824b31f8e8c852d1a6ca7d3e0ecd3cdaf654b565dc9bd05b28bfb5db3c)
        - [purchase stamp tx](https://blockscout.com/xdai/mainnet/tx/0x17bb577fc97647e052f733456c42f8333199fe34d551e73c2d857ff931afa7b9)
    - see https://roamresearch.com/#/app/swarm-org/page/57j79XxGG
- documentation
   - [ ] how to run the gateway
   - [x] postage stamps calculation
        - talked to Dan, he will include it
