### ISSUE TITLE
bzz.link reliability

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/js-team-zenhub#111]
there are reports that the bzz.link addresses work unreliably
for example Michelle reported that https://kurate.bzz.link is slow and unreliable, and the https://api.gateway.ethswarm.org/bzz/kurate.eth/ is better
however when I do some tests with https://api.gateway.ethswarm.org/bzz/swarm.eth/ I get the following results:

sometimes it returns {"message":"Not Found","code":404}. The issue here is usually this happens in a few seconds, which should not be the case, instead it should wait until timeout (~30 seconds) instead.
sometimes it returns {"message":"path address not found","code":404}. This means that Bee found a manifest that belongs to the name, however there is no entry for / (root path) in it. This is suspicious as well.
sometimes it returns the content of the html file as expected
What makes it difficult to test is that the nodes are doing caching, so if you try multiple times eventually the it finds the content and then it will be cached for a while and it will look like it's working. It would be good to find a way to find out what causes these issues (maybe with caching turned off?). Another difficulty is that these usually work with my locally running Bee lite node.

- [ ] bzz.link - sometimes retrieving manifest failes with 404 after 3 seconds
- [ ] since 1.5.0 the manifest sometimes returns a different chunk hash
- [ ] still sometimes buying 3 stamps when started

**Comment by vojtechsimetka** [comment]
I was also having issues lately, it ended up with 404 after just few seconds.
