### ISSUE TITLE
Storage incentives mechanism

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/js-team-zenhub#116]
- [ ] understand how it works
- [ ] estimate the complexity of the smart contracts and write small specs
- [ ] understand how to present this to users in UI
