### ISSUE TITLE
api gateway

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/js-team-zenhub#96]
- [x] add missing endpoints
- [x] add monitoring to the gateway-proxy (prometheus)
- [x] write down deploy plan
- [x] http://api.gateway.ethswarm.org/ to point to a Bee node
- [x] deploy to mainnet without autobuy
- [x] organize the "how to use monitoring" meeting with the infra team to better understand the system and the monitoring needs
- [x] evaluate the autobuy from the testnet logs
